# Working With Pandas Data Frames
---

* Import the pandas library as pd and read in the csv that we just wrote as a data frame using the `read_csv`.

In [1]:
import pandas as pd
df = pd.read_csv('./gapminder_final.csv')

* return the data frame from jupyter to view it (pretty)

In [2]:
df

,Unnamed: 0,country,year,pop,continent,lifeExp,gdpPercap
0,0,Afghanistan,1997,22227415.0,Asia,41.763,635.341351
1,1,Afghanistan,2002,25268405.0,Asia,42.129,726.734055
2,2,Afghanistan,2007,31889923.0,Asia,43.828,974.580338
3,3,Afghanistan,1952,8425333.0,Asia,28.801,779.445314
4,4,Afghanistan,1957,9240934.0,Asia,30.332,820.853030
5,5,Afghanistan,1962,10267083.0,Asia,31.997,853.100710
6,6,Afghanistan,1967,11537966.0,Asia,34.020,836.197138
7,7,Afghanistan,1972,13079460.0,Asia,36.088,739.981106
8,8,Afghanistan,1977,14880372.0,Asia,38.438,786.113360
9,9,Afghanistan,1982,12881816.0,Asia,39.854,978.011439
10,10,Afghanistan,1987,13867957.0,Asia,40.822,852.395945
11,11,Afghanistan,1992,16317921.0,Asia,41.674,649.341395
12,12,Albania,1952,1282697.0,Europe,55.230,1601.056136
13,13,Albania,1957,1476505.0,Europe,59.280,1942.284244
14,14,Albania,1962,1728137.0,Europe,64.820,2312.888958
15,15,Albania,1967,1984060.0,Europe,66.220,2760.196931
16,16,Albania,1972,2263554.0,Europe,67.690,3313.422188
17,17,Albania,1977,2509048.0,Europe,68.930,3533.003910
18,18,Albania,1982,2780097.0,Europe,70.420,3630.880722
19,19,Albania,1987,3075321.0,Europe,72.000,3738.932735
20,20,Albania,1992,3326498.0,Europe,71.581,2497.437901
21,21,Albania,1997,3428038.0,Europe,72.950,3193.054604
22,22,Albania,2002,3508512.0,Europe,75.651,4604.211737
23,23,Albania,2007,3600523.0,Europe,76.423,5937.029526
24,24,Algeria,1962,11000948.0,Africa,48.303,2550.816880
25,25,Algeria,1967,12760499.0,Africa,51.407,3246.991771
26,26,Algeria,1972,14760787.0,Africa,54.518,4182.663766
27,27,Algeria,1977,17152804.0,Africa,58.014,4910.416756
28,28,Algeria,1982,20033753.0,Africa,61.368,5745.160213
29,29,Algeria,1952,9279525.0,Africa,43.077,2449.008185
...,...,...,...,...,...,...,...
1674,1674,Yemen Rep.,1982,9657618.0,Asia,49.113,1977.557010
1675,1675,Yemen Rep.,1987,11219340.0,Asia,52.922,1971.741538
1676,1676,Yemen Rep.,1992,13367997.0,Asia,55.599,1879.496673
1677,1677,Yemen Rep.,1997,15826497.0,Asia,58.020,2117.484526
1678,1678,Yemen Rep.,2002,18701257.0,Asia,60.308,2234.820827
1679,1679,Yemen Rep.,2007,22211743.0,Asia,62.698,2280.769906
1680,1680,Zambia,1952,2672000.0,Africa,42.038,1147.388831
1681,1681,Zambia,1957,3016000.0,Africa,44.077,1311.956766
1682,1682,Zambia,1962,3421000.0,Africa,46.023,1452.725766
1683,1683,Zambia,1967,3900000.0,Africa,47.768,1777.077318
1684,1684,Zambia,1972,4506497.0,Africa,50.107,1773.498265
1685,1685,Zambia,1977,5216550.0,Africa,51.386,1588.688299
1686,1686,Zambia,1982,6100407.0,Africa,51.821,1408.678565
1687,1687,Zambia,1987,7272406.0,Africa,50.821,1213.315116
1688,1688,Zambia,1992,8381163.0,Africa,46.100,1210.884633
1689,1689,Zambia,1997,9417789.0,Africa,40.238,1071.353818
1690,1690,Zambia,2002,10595811.0,Africa,39.193,1071.613938
1691,1691,Zambia,2007,11746035.0,Africa,42.384,1271.211593
1692,1692,Zimbabwe,1952,3080907.0,Africa,48.451,406.884115
1693,1693,Zimbabwe,1957,3646340.0,Africa,50.469,518.764268
1694,1694,Zimbabwe,1962,4277736.0,Africa,52.358,527.272182
1695,1695,Zimbabwe,1967,4995432.0,Africa,53.995,569.795071
1696,1696,Zimbabwe,1972,5861135.0,Africa,55.635,799.362176
1697,1697,Zimbabwe,1977,6642107.0,Africa,57.674,685.587682
1698,1698,Zimbabwe,1982,7636524.0,Africa,60.363,788.855041
1699,1699,Zimbabwe,1987,9216418.0,Africa,62.351,706.157306
1700,1700,Zimbabwe,1992,10704340.0,Africa,60.377,693.420786
1701,1701,Zimbabwe,1997,11404948.0,Africa,46.809,792.449960
1702,1702,Zimbabwe,2002,11926563.0,Africa,39.989,672.038623
1703,1703,Zimbabwe,2007,12311143.0,Africa,43.487,469.709298

* What if we wanted to break up all the data into files for each continent?
* What if we wanted to have only one row for each country?
  * We would have to have columns for each year
  
** Don't worry about all of the code in the block below. By the end of this section it will make sense. **

In [4]:
allcountries_df = pd.read_csv("./gapminder_final.csv")
df_t = allcountries_df

years = sorted(list(df_t['year'].unique()))
# Convert years to strings

for year in years:
    col_name = "gdpPercap_" + str(year)
    df_t[col_name] = 0

for y in years:
    df_t.loc[df_t.year == y, "gdpPercap_" + str(y)] = df_t["gdpPercap"]

df_t = df_t.groupby(df_t["country"]).max()
df_t["pop2007"] = df_t["pop"]
df_t["lifeExp2007"] = df_t["lifeExp"]

df_t.drop("country", axis=1, inplace=True)
df_t.drop("gdpPercap", axis=1, inplace=True)
df_t.drop("year", axis=1, inplace=True)
df_t.drop("lifeExp", axis=1, inplace=True)

continents = df_t["continent"].unique()

df_t.to_csv("./gapminder_All.csv")

for continent in continents:
    new_df = df_t.loc[df_t["continent"] == continent]
    newfilename = "gapminder_" + continent + ".csv"
    #new_df.to_csv("./python-lessons" + newfilename)
    new_df.to_csv(newfilename)
    df.to_csv("./python-lessons")

* Check out our data folder after we ran this script. We now have six additional csv files.
    ~~~
    * gapminder_All.csv
    * gapminder_Oceana.csv
    * gapminder_Europe.csv
    * gapminder_Asia.csv
    * gapminder_Americas.csv
    * gapminder_Africa.csv
    ~~~

Lets read in the Africa csv to see how the structure has changed.

In [11]:
# Read in gapminder_Africa.csv as a data frame
df_africa = pd.read_csv('./gapminder_Africa.csv')
df_africa

,country,Unnamed: 0,pop,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007,pop2007,lifeExp2007
0,Algeria,35,33333216.0,Africa,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,4797.295051,5288.040382,6223.367465,33333216.0,72.301
1,Angola,47,12420476.0,Africa,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,2277.140884,2773.287312,4797.231267,12420476.0,42.731
2,Benin,131,8078314.0,Africa,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,1232.975292,1372.877931,1441.284873,8078314.0,56.728
3,Botswana,167,1639131.0,Africa,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,7954.111645,8647.142313,11003.605080,12569.851770,1639131.0,63.622
4,Burkina Faso,203,14326203.0,Africa,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,931.752773,946.294962,1037.645221,1217.032994,14326203.0,52.295
5,Burundi,215,8390505.0,Africa,339.296459,379.564628,355.203227,412.977514,464.099504,556.103265,559.603231,621.818819,631.699878,463.115148,446.403513,430.070692,8390505.0,49.580
6,Cameroon,239,17696293.0,Africa,1172.667655,1313.048099,1399.607441,1508.453148,1684.146528,1783.432873,2367.983282,2602.664206,1793.163278,1694.337469,1934.011449,2042.095240,17696293.0,54.985
7,Central African Republic,263,4369038.0,Africa,1071.310713,1190.844328,1193.068753,1136.056615,1070.013275,1109.374338,956.752991,844.876350,747.905525,740.506332,738.690607,706.016537,4369038.0,50.485
8,Chad,275,10238807.0,Africa,1178.665927,1308.495577,1389.817618,1196.810565,1104.103987,1133.984950,797.908101,952.386129,1058.064300,1004.961353,1156.181860,1704.063724,10238807.0,51.724
9,Comoros,323,710960.0,Africa,1102.990936,1211.148548,1406.648278,1876.029643,1937.577675,1172.603047,1267.100083,1315.980812,1246.907370,1173.618235,1075.811558,986.147879,710960.0,65.152
10,Congo Dem. Rep.,335,64606759.0,Africa,780.542326,905.860230,896.314634,861.593242,904.896069,795.757282,673.747818,672.774812,457.719181,312.188423,241.165877,277.551859,64606759.0,47.804
11,Congo Rep.,347,3800610.0,Africa,2125.621418,2315.056572,2464.783157,2677.939642,3213.152683,3259.178978,4879.507522,4201.194937,4016.239529,3484.164376,3484.061970,3632.557798,3800610.0,57.470
12,Cote d'Ivoire,371,18013409.0,Africa,1388.594732,1500.895925,1728.869428,2052.050473,2378.201111,2517.736547,2602.710169,2156.956069,1648.073791,1786.265407,1648.800823,1544.750112,18013409.0,54.655
13,Djibouti,431,496374.0,Africa,2669.529475,2864.969076,3020.989263,3020.050513,3694.212352,3081.761022,2879.468067,2880.102568,2377.156192,1895.016984,1908.260867,2082.481567,496374.0,54.791
14,Egypt,467,80264543.0,Africa,1418.822445,1458.915272,1693.335853,1814.880728,2024.008147,2785.493582,3503.729636,3885.460710,3794.755195,4173.181797,4754.604414,5581.180998,80264543.0,71.338
15,Equatorial Guinea,491,551201.0,Africa,375.643123,426.096408,582.841971,915.596003,672.412257,958.566812,927.825343,966.896815,1132.055034,2814.480755,7703.495900,12154.089750,551201.0,51.579
16,Eritrea,503,4906585.0,Africa,328.940557,344.161886,380.995843,468.794970,514.324208,505.753808,524.875849,521.134133,582.858510,913.470790,765.350001,641.369524,4906585.0,58.040
17,Ethiopia,515,76511887.0,Africa,362.146280,378.904163,419.456416,516.118644,566.243944,556.808383,577.860747,573.741314,421.353465,515.889401,530.053532,690.805576,76511887.0,52.947
18,Gabon,551,1454867.0,Africa,4293.476475,4976.198099,6631.459222,8358.761987,11401.948410,21745.573280,15113.361940,11864.408440,13522.157520,14722.841880,12521.713920,13206.484520,1454867.0,61.366
19,Gambia,563,1688359.0,Africa,485.230659,520.926711,599.650276,734.782912,756.086836,884.755251,835.809611,611.658861,665.624413,653.730170,660.585600,752.749726,1688359.0,59.448
20,Ghana,587,22873338.0,Africa,911.298937,1043.561537,1190.041118,1125.697160,1178.223708,993.223957,876.032569,847.006113,925.060154,1005.245812,1111.984578,1327.608910,22873338.0,60.022
21,Guinea,635,9947814.0,Africa,510.196492,576.267025,686.373674,708.759541,741.666231,874.685864,857.250358,805.572472,794.348438,869.449767,945.583584,942.654211,9947814.0,56.007
22,Guinea-Bissau,623,1472041.0,Africa,299.850319,431.790457,522.034373,715.580640,820.224588,764.725963,838.123967,736.415392,745.539871,796.664468,575.704718,579.231743,1472041.0,46.388
23,Kenya,827,35610177.0,Africa,853.540919,944.438315,896.966373,1056.736457,1222.359968,1267.613204,1348.225791,1361.936856,1341.921721,1360.485021,1287.514732,1463.249282,35610177.0,59.339
24,Lesotho,887,2046772.0,Africa,298.846212,335.997115,411.800627,498.639026,496.581592,745.369541,797.263107,773.993214,977.486272,1186.147994,1275.184575,1569.331442,2046772.0,59.685
25,Liberia,899,3193942.0,Africa,575.572996,620.969990,634.195163,713.603648,803.005454,640.322438,572.199569,506.113857,636.622919,609.173951,531.482368,414.507341,3193942.0,46.027
26,Libya,911,6036914.0,Africa,2387.548060,3448.284395,6757.030816,18772.751690,21011.497210,21951.211760,17364.275380,11770.589800,9640.138501,9467.446056,9534.677467,12057.499280,6036914.0,73.952
27,Madagascar,923,19167654.0,Africa,1443.011715,1589.202750,1643.387110,1634.047282,1748.562982,1544.228586,1302.878658,1155.441948,1040.676190,986.295896,894.637082,1044.770126,19167654.0,59.443
28,Malawi,935,13327079.0,Africa,369.165080,416.369806,427.901086,495.514781,584.621971,663.223677,632.803921,635.517363,563.200014,692.275810,665.423119,759.349910,13327079.0,49.420
29,Mali,959,12031795.0,Africa,452.336981,490.382187,496.174343,545.009887,581.368876,686.395269,618.014064,684.171558,739.014375,790.257985,951.409752,1042.581557,12031795.0,54.467
30,Mauritania,971,3270065.0,Africa,743.115910,846.120261,1055.896036,1421.145193,1586.851781,1497.492223,1481.150189,1421.603576,1361.369784,1483.136136,1579.019543,1803.151496,3270065.0,64.164
31,Mauritius,983,1250882.0,Africa,1967.955707,2034.037981,2529.067487,2475.387562,2575.484158,3710.982963,3688.037739,4783.586903,6058.253846,7425.705295,9021.815894,10956.991120,1250882.0,72.801
32,Morocco,1031,33757175.0,Africa,1688.203570,1642.002314,1566.353493,1711.044770,1930.194975,2370.619976,2702.620356,2755.046991,2948.047252,2982.101858,3258.495584,3820.175230,33757175.0,71.164
33,Mozambique,1043,19951656.0,Africa,468.526038,495.586833,556.686354,566.669154,724.917804,502.319733,462.211415,389.876185,410.896824,472.346077,633.617947,823.685621,19951656.0,46.344
34,Namibia,1067,2055080.0,Africa,2423.780443,2621.448058,3173.215595,3793.694753,3746.080948,3876.485958,4191.100511,3693.731337,3804.537999,3899.524260,4072.324751,4811.060429,2055080.0,61.999
35,Niger,1127,12894865.0,Africa,761.879376,835.523403,997.766113,1054.384891,954.209236,808.897073,909.722135,668.300023,581.182725,580.305209,601.074501,619.676892,12894865.0,56.867
36,Nigeria,1139,135031164.0,Africa,1077.281856,1100.592563,1150.927478,1014.514104,1698.388838,1981.951806,1576.973750,1385.029563,1619.848217,1624.941275,1615.286395,2013.977305,135031164.0,47.472
37,Reunion,1271,798094.0,Africa,2718.885295,2769.451844,3173.723340,4021.175739,5047.658563,4319.804067,5267.219353,5303.377488,6101.255823,6071.941411,6316.165200,7670.122558,798094.0,76.442
38,Rwanda,1295,8860588.0,Africa,493.323875,540.289398,597.473073,510.963714,590.580664,670.080601,881.570647,847.991217,737.068595,589.944505,785.653765,863.088464,8860588.0,46.242
39,Sao Tome and Principe,1307,199579.0,Africa,879.583586,860.736903,1071.551119,1384.840593,1532.985254,1737.561657,1890.218117,1516.525457,1428.777814,1339.076036,1353.092390,1598.435089,199579.0,65.528
40,Senegal,1331,12267493.0,Africa,1450.356983,1567.653006,1654.988723,1612.404632,1597.712056,1561.769116,1518.479984,1441.720720,1367.899369,1392.368347,1519.635262,1712.472136,12267493.0,63.062
41,Sierra Leone,1355,6144562.0,Africa,879.787736,1004.484437,1116.639877,1206.043465,1353.759762,1348.285159,1465.010784,1294.447788,1068.696278,574.648158,699.489713,862.540756,6144562.0,42.568
42,Somalia,1403,9118773.0,Africa,1135.749842,1258.147413,1369.488336,1284.733180,1254.576127,1450.992513,1176.807031,1093.244963,926.960296,930.596428,882.081822,926.141068,9118773.0,48.159
43,South Africa,1415,44433622.0,Africa,4725.295531,5487.104219,5768.729717,7114.477971,7765.962636,8028.651439,8568.266228,7825.823398,7225.069258,7479.188244,7710.946444,9269.657808,44433622.0,61.888
44,Sudan,1451,42292929.0,Africa,1615.991129,1770.337074,1959.593767,1687.997641,1659.652775,2202.988423,1895.544073,1507.819159,1492.197043,1632.210764,1993.398314,2602.394995,42292929.0,58.556
45,Swaziland,1463,1133066.0,Africa,1148.376626,1244.708364,1856.182125,2613.101665,3364.836625,3781.410618,3895.384018,3984.839812,3553.022400,3876.768460,4128.116943,4513.480643,1133066.0,58.474
46,Tanzania,1523,38139640.0,Africa,716.650072,698.535607,722.003807,848.218657,915.985059,962.492293,874.242607,831.822079,825.682454,789.186223,899.074211,1107.482182,38139640.0,52.517
47,Togo,1547,5701579.0,Africa,859.808657,925.908320,1067.534810,1477.596760,1649.660188,1532.776998,1344.577953,1202.201361,1034.298904,982.286924,886.220577,882.969944,5701579.0,58.420
48,Tunisia,1571,10276158.0,Africa,1468.475631,1395.232468,1660.303210,1932.360167,2753.285994,3120.876811,3560.233174,3810.419296,4332.720164,4876.798614,5722.895655,7092.923025,10276158.0,73.923
49,Uganda,1595,29170398.0,Africa,734.753484,774.371069,767.271740,908.918522,950.735869,843.733137,682.266227,617.724406,644.170797,816.559081,927.721002,1056.380121,29170398.0,51.542
50,Zambia,1691,11746035.0,Africa,1147.388831,1311.956766,1452.725766,1777.077318,1773.498265,1588.688299,1408.678565,1213.315116,1210.884633,1071.353818,1071.613938,1271.211593,11746035.0,51.821
51,Zimbabwe,1703,12311143.0,Africa,406.884115,518.764268,527.272182,569.795071,799.362176,685.587682,788.855041,706.157306,693.420786,792.449960,672.038623,469.709298,12311143.0,62.351

We can see that now there is only one row for each country. Lets re-read the file using the index_col parameter

In [12]:
# Re-read the file using index_cols
#df_africa = pd.read_csv('gapminder_Africa.csv', index_col='country')
#df_africa

df_all = pd.read_csv('gapminder_All.csv')#, index_col='country')
df_all

,country,Unnamed: 0,pop,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007,pop2007,lifeExp2007
0,Afghanistan,11,3.188992e+07,Asia,779.445314,820.853030,853.100710,836.197138,739.981106,786.113360,978.011439,852.395945,649.341395,635.341351,726.734055,974.580338,3.188992e+07,43.828
1,Albania,23,3.600523e+06,Europe,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526,3.600523e+06,76.423
2,Algeria,35,3.333322e+07,Africa,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,4797.295051,5288.040382,6223.367465,3.333322e+07,72.301
3,Angola,47,1.242048e+07,Africa,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,2277.140884,2773.287312,4797.231267,1.242048e+07,42.731
4,Argentina,59,4.030193e+07,Americas,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,8797.640716,12779.379640,4.030193e+07,75.320
5,Australia,71,2.043418e+07,Oceania,10039.595640,10949.649590,12217.226860,14526.124650,16788.629480,18334.197510,19477.009280,21888.889030,23424.766830,26997.936570,30687.754730,34435.367440,2.043418e+07,81.235
6,Austria,83,8.199783e+06,Europe,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700,8.199783e+06,79.829
7,Bahrain,95,7.085730e+05,Asia,9867.084765,11635.799450,12753.275140,14804.672700,18268.658390,19340.101960,19211.147310,18524.024060,19035.579170,20292.016790,23403.559270,29796.048340,7.085730e+05,75.635
8,Bangladesh,107,1.504483e+08,Asia,684.244172,661.637458,686.341554,721.186086,630.233627,659.877232,676.981866,751.979403,837.810164,972.770035,1136.390430,1391.253792,1.504483e+08,64.062
9,Belgium,119,1.039223e+07,Europe,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080,1.039223e+07,79.441
10,Benin,131,8.078314e+06,Africa,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,1232.975292,1372.877931,1441.284873,8.078314e+06,56.728
11,Bolivia,143,9.119152e+06,Americas,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,3326.143191,3413.262690,3822.137084,9.119152e+06,65.554
12,Bosnia and Herzegovina,155,4.552198e+06,Europe,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803,4.552198e+06,74.852
13,Botswana,167,1.639131e+06,Africa,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,7954.111645,8647.142313,11003.605080,12569.851770,1.639131e+06,63.622
14,Brazil,179,1.900106e+08,Americas,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,7957.980824,8131.212843,9065.800825,1.900106e+08,72.390
15,Bulgaria,191,8.971958e+06,Europe,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820,8.971958e+06,73.005
16,Burkina Faso,203,1.432620e+07,Africa,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,931.752773,946.294962,1037.645221,1217.032994,1.432620e+07,52.295
17,Burundi,215,8.390505e+06,Africa,339.296459,379.564628,355.203227,412.977514,464.099504,556.103265,559.603231,621.818819,631.699878,463.115148,446.403513,430.070692,8.390505e+06,49.580
18,Cambodia,227,1.413186e+07,Asia,368.469286,434.038336,496.913648,523.432314,421.624026,524.972183,624.475478,683.895573,682.303175,734.285170,896.226015,1713.778686,1.413186e+07,59.723
19,Cameroon,239,1.769629e+07,Africa,1172.667655,1313.048099,1399.607441,1508.453148,1684.146528,1783.432873,2367.983282,2602.664206,1793.163278,1694.337469,1934.011449,2042.095240,1.769629e+07,54.985
20,Canada,251,3.339014e+07,Americas,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,28954.925890,33328.965070,36319.235010,3.339014e+07,80.653
21,Central African Republic,263,4.369038e+06,Africa,1071.310713,1190.844328,1193.068753,1136.056615,1070.013275,1109.374338,956.752991,844.876350,747.905525,740.506332,738.690607,706.016537,4.369038e+06,50.485
22,Chad,275,1.023881e+07,Africa,1178.665927,1308.495577,1389.817618,1196.810565,1104.103987,1133.984950,797.908101,952.386129,1058.064300,1004.961353,1156.181860,1704.063724,1.023881e+07,51.724
23,Chile,287,1.628474e+07,Americas,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,10118.053180,10778.783850,13171.638850,1.628474e+07,78.553
24,China,299,1.318683e+09,Asia,400.448611,575.987001,487.674018,612.705693,676.900092,741.237470,962.421380,1378.904018,1655.784158,2289.234136,3119.280896,4959.114854,1.318683e+09,72.961
25,Colombia,311,4.422755e+07,Americas,2144.115096,2323.805581,2492.351109,2678.729839,3264.660041,3815.807870,4397.575659,4903.219100,5444.648617,6117.361746,5755.259962,7006.580419,4.422755e+07,72.889
26,Comoros,323,7.109600e+05,Africa,1102.990936,1211.148548,1406.648278,1876.029643,1937.577675,1172.603047,1267.100083,1315.980812,1246.907370,1173.618235,1075.811558,986.147879,7.109600e+05,65.152
27,Congo Dem. Rep.,335,6.460676e+07,Africa,780.542326,905.860230,896.314634,861.593242,904.896069,795.757282,673.747818,672.774812,457.719181,312.188423,241.165877,277.551859,6.460676e+07,47.804
28,Congo Rep.,347,3.800610e+06,Africa,2125.621418,2315.056572,2464.783157,2677.939642,3213.152683,3259.178978,4879.507522,4201.194937,4016.239529,3484.164376,3484.061970,3632.557798,3.800610e+06,57.470
29,Costa Rica,359,4.133884e+06,Americas,2627.009471,2990.010802,3460.937025,4161.727834,5118.146939,5926.876967,5262.734751,5629.915318,6160.416317,6677.045314,7723.447195,9645.061420,4.133884e+06,78.782
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,Sierra Leone,1355,6.144562e+06,Africa,879.787736,1004.484437,1116.639877,1206.043465,1353.759762,1348.285159,1465.010784,1294.447788,1068.696278,574.648158,699.489713,862.540756,6.144562e+06,42.568
113,Singapore,1367,4.553009e+06,Asia,2315.138227,2843.104409,3674.735572,4977.418540,8597.756202,11210.089480,15169.161120,18861.530810,24769.891200,33519.476600,36023.105400,47143.179640,4.553009e+06,79.972
114,Slovak Republic,1379,5.447502e+06,Europe,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,10922.664040,11348.545850,12037.267580,9498.467723,12126.230650,13638.778370,18678.314350,5.447502e+06,74.663
115,Slovenia,1391,2.011612e+06,Europe,4215.041741,5862.276629,7402.303395,9405.489397,12383.486200,15277.030170,17866.721750,18678.534920,14214.716810,17161.107350,20660.019360,25768.257590,2.011612e+06,77.926
116,Somalia,1403,9.118773e+06,Africa,1135.749842,1258.147413,1369.488336,1284.733180,1254.576127,1450.992513,1176.807031,1093.244963,926.960296,930.596428,882.081822,926.141068,9.118773e+06,48.159
117,South Africa,1415,4.443362e+07,Africa,4725.295531,5487.104219,5768.729717,7114.477971,7765.962636,8028.651439,8568.266228,7825.823398,7225.069258,7479.188244,7710.946444,9269.657808,4.443362e+07,61.888
118,Spain,1427,4.044819e+07,Europe,3834.034742,4564.802410,5693.843879,7993.512294,10638.751310,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700,4.044819e+07,80.941
119,Sri Lanka,1439,2.037824e+07,Asia,1083.532030,1072.546602,1074.471960,1135.514326,1213.395530,1348.775651,1648.079789,1876.766827,2153.739222,2664.477257,3015.378833,3970.095407,2.037824e+07,72.396
120,Sudan,1451,4.229293e+07,Africa,1615.991129,1770.337074,1959.593767,1687.997641,1659.652775,2202.988423,1895.544073,1507.819159,1492.197043,1632.210764,1993.398314,2602.394995,4.229293e+07,58.556
121,Swaziland,1463,1.133066e+06,Africa,1148.376626,1244.708364,1856.182125,2613.101665,3364.836625,3781.410618,3895.384018,3984.839812,3553.022400,3876.768460,4128.116943,4513.480643,1.133066e+06,58.474
122,Sweden,1475,9.031088e+06,Europe,8527.844662,9911.878226,12329.441920,15258.296970,17832.024640,18855.725210,20667.381250,23586.929270,23880.016830,25266.594990,29341.630930,33859.748350,9.031088e+06,80.884
123,Switzerland,1487,7.554661e+06,Europe,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070,7.554661e+06,81.701
124,Syria,1499,1.931475e+07,Asia,1643.485354,2117.234893,2193.037133,1881.923632,2571.423014,3195.484582,3761.837715,3116.774285,3340.542768,4014.238972,4090.925331,4184.548089,1.931475e+07,74.143
125,Taiwan,1511,2.317429e+07,Asia,1206.947913,1507.861290,1822.879028,2643.858681,4062.523897,5596.519826,7426.354774,11054.561750,15215.657900,20206.820980,23235.423290,28718.276840,2.317429e+07,78.400
126,Tanzania,1523,3.813964e+07,Africa,716.650072,698.535607,722.003807,848.218657,915.985059,962.492293,874.242607,831.822079,825.682454,789.186223,899.074211,1107.482182,3.813964e+07,52.517
127,Thailand,1535,6.506815e+07,Asia,757.797418,793.577415,1002.199172,1295.460660,1524.358936,1961.224635,2393.219781,2982.653773,4616.896545,5852.625497,5913.187529,7458.396327,6.506815e+07,70.616
128,Togo,1547,5.701579e+06,Africa,859.808657,925.908320,1067.534810,1477.596760,1649.660188,1532.776998,1344.577953,1202.201361,1034.298904,982.286924,886.220577,882.969944,5.701579e+06,58.420
129,Trinidad and Tobago,1559,1.191336e+06,Americas,3023.271928,4100.393400,4997.523971,5621.368472,6619.551419,7899.554209,9119.528607,7388.597823,7370.990932,8792.573126,11460.600230,18008.509240,1.191336e+06,69.862
130,Tunisia,1571,1.027616e+07,Africa,1468.475631,1395.232468,1660.303210,1932.360167,2753.285994,3120.876811,3560.233174,3810.419296,4332.720164,4876.798614,5722.895655,7092.923025,1.027616e+07,73.923
131,Turkey,1583,7.115865e+07,Europe,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384,7.115865e+07,71.777
132,Uganda,1595,2.917040e+07,Africa,734.753484,774.371069,767.271740,908.918522,950.735869,843.733137,682.266227,617.724406,644.170797,816.559081,927.721002,1056.380121,2.917040e+07,51.542
133,United Kingdom,1607,6.077624e+07,Europe,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280,6.077624e+07,79.425
134,United States,1619,3.011399e+08,Americas,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,35767.433030,39097.099550,42951.653090,3.011399e+08,78.242
135,Uruguay,1631,3.447496e+06,Americas,5716.766744,6150.772969,5603.357717,5444.619620,5703.408898,6504.339663,6920.223051,7452.398969,8137.004775,9230.240708,7727.002004,10611.462990,3.447496e+06,76.384
136,Venezuela,1643,2.608466e+07,Americas,7689.799761,9802.466526,8422.974165,9541.474188,10505.259660,13143.950950,11152.410110,9883.584648,10733.926310,10165.495180,8605.047831,11415.805690,2.608466e+07,73.747
137,Vietnam,1655,8.526236e+07,Asia,605.066492,676.285448,772.049160,637.123289,699.501644,713.537120,707.235786,820.799445,989.023149,1385.896769,1764.456677,2441.576404,8.526236e+07,74.249
138,West Bank and Gaza,1667,4.018332e+06,Asia,1515.592329,1827.067742,2198.956312,2649.715007,3133.409277,3682.831494,4336.032082,5107.197384,6017.654756,7110.667619,4515.487575,3025.349798,4.018332e+06,73.422
139,Yemen Rep.,1679,2.221174e+07,Asia,781.717576,804.830455,825.623201,862.442146,1265.047031,1829.765177,1977.557010,1971.741538,1879.496673,2117.484526,2234.820827,2280.769906,2.221174e+07,62.698
140,Zambia,1691,1.174604e+07,Africa,1147.388831,1311.956766,1452.725766,1777.077318,1773.498265,1588.688299,1408.678565,1213.315116,1210.884633,1071.353818,1071.613938,1271.211593,1.174604e+07,51.821
141,Zimbabwe,1703,1.231114e+07,Africa,406.884115,518.764268,527.272182,569.795071,799.362176,685.587682,788.855041,706.157306,693.420786,792.449960,672.038623,469.709298,1.231114e+07,62.351

## Inspecting Data
We've already see how we can get information about a dataframe using the `.info()` and `.describe()` functions, but there are many ways to get information and view a data frame

* Can also use describe() on data frame selections (like a single column)

In [13]:
# Use the .describe() function on the "gdpPercap" column
#df_africa.info()
df_all.describe()

,Unnamed: 0,pop,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007,pop2007,lifeExp2007
count,142.000000,1.420000e+02,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,1.420000e+02,142.000000
mean,857.000000,4.404920e+07,3725.276046,4299.408345,4725.812342,5483.653047,6770.082815,7313.166421,7518.901673,7900.920218,8158.608521,9090.175363,9917.848365,11680.071820,4.404920e+07,68.035415
std,493.631441,1.476159e+08,9321.064786,9869.662202,8667.362525,8095.315431,10614.383403,8362.489150,7733.845006,8288.281304,9031.846080,10171.493263,11154.114865,12859.937337,1.476159e+08,10.784702
min,11.000000,1.995790e+05,298.846212,335.997115,355.203227,349.000000,357.000000,371.000000,424.000000,385.000000,347.000000,312.188423,241.165877,277.551859,1.995790e+05,42.568000
25%,434.000000,4.508559e+06,864.752389,930.540819,1059.149171,1151.245103,1257.193853,1357.257252,1363.338985,1327.469823,1270.660958,1366.837958,1409.567264,1624.842248,4.508559e+06,59.694500
50%,857.000000,1.067419e+07,1968.528344,2173.220291,2335.439533,2678.334741,3339.129407,3798.609244,4216.228428,4280.300366,4386.085502,4781.825478,5319.804524,6124.371109,1.067419e+07,71.935500
75%,1280.000000,3.121004e+07,3913.492777,4876.356362,5709.381428,7075.932943,9508.839303,11204.102423,12347.953723,11994.052795,10684.351870,12022.867188,13359.512257,18008.835640,3.121004e+07,76.413250
max,1703.000000,1.318683e+09,108382.352900,113523.132900,95458.111760,80894.883260,109347.867000,59265.477140,33693.175250,31540.974800,34932.919590,41283.164330,44683.975250,49357.190170,1.318683e+09,82.603000

* We can print the first or last x number of rows of our data frame using the head() and tails() functions.

In [14]:
# heads() function
#df_africa.head()
df_all.head(10)

,country,Unnamed: 0,pop,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007,pop2007,lifeExp2007
0,Afghanistan,11,31889923.0,Asia,779.445314,820.853030,853.100710,836.197138,739.981106,786.113360,978.011439,852.395945,649.341395,635.341351,726.734055,974.580338,31889923.0,43.828
1,Albania,23,3600523.0,Europe,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526,3600523.0,76.423
2,Algeria,35,33333216.0,Africa,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,4797.295051,5288.040382,6223.367465,33333216.0,72.301
3,Angola,47,12420476.0,Africa,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,2277.140884,2773.287312,4797.231267,12420476.0,42.731
4,Argentina,59,40301927.0,Americas,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,8797.640716,12779.379640,40301927.0,75.320
5,Australia,71,20434176.0,Oceania,10039.595640,10949.649590,12217.226860,14526.124650,16788.629480,18334.197510,19477.009280,21888.889030,23424.766830,26997.936570,30687.754730,34435.367440,20434176.0,81.235
6,Austria,83,8199783.0,Europe,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700,8199783.0,79.829
7,Bahrain,95,708573.0,Asia,9867.084765,11635.799450,12753.275140,14804.672700,18268.658390,19340.101960,19211.147310,18524.024060,19035.579170,20292.016790,23403.559270,29796.048340,708573.0,75.635
8,Bangladesh,107,150448339.0,Asia,684.244172,661.637458,686.341554,721.186086,630.233627,659.877232,676.981866,751.979403,837.810164,972.770035,1136.390430,1391.253792,150448339.0,64.062
9,Belgium,119,10392226.0,Europe,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080,10392226.0,79.441

In [32]:
# tails() function
#df_africa.tail()
df_all.tail(3)

,Unnamed: 0,pop,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007,pop2007,lifeExp2007
country,,,,,,,,,,,,,,,,,
Yemen Rep.,1679,22211743.0,Asia,781.717576,804.830455,825.623201,862.442146,1265.047031,1829.765177,1977.557010,1971.741538,1879.496673,2117.484526,2234.820827,2280.769906,22211743.0,62.698
Zambia,1691,11746035.0,Africa,1147.388831,1311.956766,1452.725766,1777.077318,1773.498265,1588.688299,1408.678565,1213.315116,1210.884633,1071.353818,1071.613938,1271.211593,11746035.0,51.821
Zimbabwe,1703,12311143.0,Africa,406.884115,518.764268,527.272182,569.795071,799.362176,685.587682,788.855041,706.157306,693.420786,792.449960,672.038623,469.709298,12311143.0,62.351

* **Note:** head() and tail() default to 5 rows worth of data. We can also pass a value to either to get more or less rows.
  * E.g.  
  head(10)
  
 ---
  
* Use `.dtypes` method to get the data type for each column

In [15]:
# Write your code here
#df_africa.dtypes
df_all.dtypes

country            object
Unnamed: 0          int64
pop               float64
continent          object
gdpPercap_1952    float64
gdpPercap_1957    float64
gdpPercap_1962    float64
gdpPercap_1967    float64
gdpPercap_1972    float64
gdpPercap_1977    float64
gdpPercap_1982    float64
gdpPercap_1987    float64
gdpPercap_1992    float64
gdpPercap_1997    float64
gdpPercap_2002    float64
gdpPercap_2007    float64
pop2007           float64
lifeExp2007       float64
dtype: object

* Use `shape` method to get the row and column numbers

In [16]:
# Write your code here
#df_africa.shape
df_all.shape

(142, 18)

Here we can see the that the data have 52 rows of data and 18 attributes worth of information.

* Use the `len()` function to get numbers of each individually

In [18]:
# print number of rows of data
len(df_all.index)

142

In [19]:
# print number of columns of data
len(df_all.columns)

18

* As seen before we can pass the data frame a column name to get all values for that column


* Print out only the lifeExp2007 column from the data frame

In [20]:
# Write your code here
df_all['lifeExp2007']

0      43.828
1      76.423
2      72.301
3      42.731
4      75.320
5      81.235
6      79.829
7      75.635
8      64.062
9      79.441
10     56.728
11     65.554
12     74.852
13     63.622
14     72.390
15     73.005
16     52.295
17     49.580
18     59.723
19     54.985
20     80.653
21     50.485
22     51.724
23     78.553
24     72.961
25     72.889
26     65.152
27     47.804
28     57.470
29     78.782
        ...
112    42.568
113    79.972
114    74.663
115    77.926
116    48.159
117    61.888
118    80.941
119    72.396
120    58.556
121    58.474
122    80.884
123    81.701
124    74.143
125    78.400
126    52.517
127    70.616
128    58.420
129    69.862
130    73.923
131    71.777
132    51.542
133    79.425
134    78.242
135    76.384
136    73.747
137    74.249
138    73.422
139    62.698
140    51.821
141    62.351
Name: lifeExp2007, Length: 142, dtype: float64

---
## EXERCISE:
1. How many different country names are there in the gapminder_all.csv file?

---

In [24]:
# Write your code here
countries = sorted(list(df_all['country'].unique()))
#years = sorted(list(df_t['year'].unique()))
#df_all
len(countries)

142

---
## EXERCISE:
1. What is the last country listed in the Africa data frame?

---

In [29]:
# Write your code here
df_africa = pd.read_csv('gapminder_Africa.csv')
df_africa
africanCountries = sorted(list(df_africa['country'].unique()))
df_africa.tail(1)

,country,Unnamed: 0,pop,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007,pop2007,lifeExp2007
51,Zimbabwe,1703,12311143.0,Africa,406.884115,518.764268,527.272182,569.795071,799.362176,685.587682,788.855041,706.157306,693.420786,792.44996,672.038623,469.709298,12311143.0,62.351

---
## Get information about a particular column

* Operations like mean, max, min, can be used on individual columns
  * E.g. `df['year'].min()`

In [31]:
# What is the minimum value in the year column?
df_all2 = pd.read_csv('gapminder_final.csv')
df_all2['year'].min()

1952

---
## EXERCISE:
1. What is the mean life expectancy in 2007 for all countries in all years

1. What is the max population in 2007 for all countries in all years

1. What is the standard deviation for GDP per capita for all countries in all years

In [39]:
df3 = pd.read_csv("gapminder_all.csv")
# Mean Life Expectancy in 2007
avlifeexp = df3['lifeExp2007'].mean()
print(avlifeexp)
# Max Population in 2007
maxpop=df3['pop2007'].max()
print(maxpop)
# Standard Deviation of GDP per capita in 1952
df3.columns
df3['gdpPercap_1952'].std()

68.03541549295775
1318683096.0

9321.064786416604

## Rearange Columns

* This is difficult to do using a csv library or by hand
* The reverse() function will reverse the ordering of a list
     * E.g.   `['a', 'b', 'c']` to `['c', 'b', 'a']`

In [41]:
# Use the python list() function to get the data frame columns a s list
cols = list(df3.columns)
print( cols )

# use the .reverse() function to reverse the ordering of the columns
cols.reverse()
print ( cols )

['country', 'Unnamed: 0', 'pop', 'continent', 'gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967', 'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987', 'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007', 'pop2007', 'lifeExp2007']
['lifeExp2007', 'pop2007', 'gdpPercap_2007', 'gdpPercap_2002', 'gdpPercap_1997', 'gdpPercap_1992', 'gdpPercap_1987', 'gdpPercap_1982', 'gdpPercap_1977', 'gdpPercap_1972', 'gdpPercap_1967', 'gdpPercap_1962', 'gdpPercap_1957', 'gdpPercap_1952', 'continent', 'pop', 'Unnamed: 0', 'country']

* Using that now reversed list above, we can pass the list to the new data frame to reorder the columns

In [46]:
# Pass the cols variable to the data frame to re-arrange the columns
import pandas as pd
newDF = df3[cols]
newDF

,lifeExp2007,pop2007,gdpPercap_2007,gdpPercap_2002,gdpPercap_1997,gdpPercap_1992,gdpPercap_1987,gdpPercap_1982,gdpPercap_1977,gdpPercap_1972,gdpPercap_1967,gdpPercap_1962,gdpPercap_1957,gdpPercap_1952,continent,pop,Unnamed: 0,country
0,43.828,3.188992e+07,974.580338,726.734055,635.341351,649.341395,852.395945,978.011439,786.113360,739.981106,836.197138,853.100710,820.853030,779.445314,Asia,3.188992e+07,11,Afghanistan
1,76.423,3.600523e+06,5937.029526,4604.211737,3193.054604,2497.437901,3738.932735,3630.880722,3533.003910,3313.422188,2760.196931,2312.888958,1942.284244,1601.056136,Europe,3.600523e+06,23,Albania
2,72.301,3.333322e+07,6223.367465,5288.040382,4797.295051,5023.216647,5681.358539,5745.160213,4910.416756,4182.663766,3246.991771,2550.816880,3013.976023,2449.008185,Africa,3.333322e+07,35,Algeria
3,42.731,1.242048e+07,4797.231267,2773.287312,2277.140884,2627.845685,2430.208311,2756.953672,3008.647355,5473.288005,5522.776375,4269.276742,3827.940465,3520.610273,Africa,1.242048e+07,47,Angola
4,75.320,4.030193e+07,12779.379640,8797.640716,10967.281950,9308.418710,9139.671389,8997.897412,10079.026740,9443.038526,8052.953021,7133.166023,6856.856212,5911.315053,Americas,4.030193e+07,59,Argentina
5,81.235,2.043418e+07,34435.367440,30687.754730,26997.936570,23424.766830,21888.889030,19477.009280,18334.197510,16788.629480,14526.124650,12217.226860,10949.649590,10039.595640,Oceania,2.043418e+07,71,Australia
6,79.829,8.199783e+06,36126.492700,32417.607690,29095.920660,27042.018680,23687.826070,21597.083620,19749.422300,16661.625600,12834.602400,10750.721110,8842.598030,6137.076492,Europe,8.199783e+06,83,Austria
7,75.635,7.085730e+05,29796.048340,23403.559270,20292.016790,19035.579170,18524.024060,19211.147310,19340.101960,18268.658390,14804.672700,12753.275140,11635.799450,9867.084765,Asia,7.085730e+05,95,Bahrain
8,64.062,1.504483e+08,1391.253792,1136.390430,972.770035,837.810164,751.979403,676.981866,659.877232,630.233627,721.186086,686.341554,661.637458,684.244172,Asia,1.504483e+08,107,Bangladesh
9,79.441,1.039223e+07,33692.605080,30485.883750,27561.196630,25575.570690,22525.563080,20979.845890,19117.974480,16672.143560,13149.041190,10991.206760,9714.960623,8343.105127,Europe,1.039223e+07,119,Belgium
10,56.728,8.078314e+06,1441.284873,1372.877931,1232.975292,1191.207681,1225.856010,1277.897616,1029.161251,1085.796879,1035.831411,949.499064,959.601080,1062.752200,Africa,8.078314e+06,131,Benin
11,65.554,9.119152e+06,3822.137084,3413.262690,3326.143191,2961.699694,2753.691490,3156.510452,3548.097832,2980.331339,2586.886053,2180.972546,2127.686326,2677.326347,Americas,9.119152e+06,143,Bolivia
12,74.852,4.552198e+06,7446.298803,6018.975239,4766.355904,2546.781445,4314.114757,4126.613157,3528.481305,2860.169750,2172.352423,1709.683679,1353.989176,973.533195,Europe,4.552198e+06,155,Bosnia and Herzegovina
13,63.622,1.639131e+06,12569.851770,11003.605080,8647.142313,7954.111645,6205.883850,4551.142150,3214.857818,2263.611114,1214.709294,983.653976,918.232535,851.241141,Africa,1.639131e+06,167,Botswana
14,72.390,1.900106e+08,9065.800825,8131.212843,7957.980824,6950.283021,7807.095818,7030.835878,6660.118654,4985.711467,3429.864357,3336.585802,2487.365989,2108.944355,Americas,1.900106e+08,179,Brazil
15,73.005,8.971958e+06,10680.792820,7696.777725,5970.388760,6302.623438,8239.854824,8224.191647,7612.240438,6597.494398,5577.002800,4254.337839,3008.670727,2444.286648,Europe,8.971958e+06,191,Bulgaria
16,52.295,1.432620e+07,1217.032994,1037.645221,946.294962,931.752773,912.063142,807.198586,743.387037,854.735976,794.826560,722.512021,617.183465,543.255241,Africa,1.432620e+07,203,Burkina Faso
17,49.580,8.390505e+06,430.070692,446.403513,463.115148,631.699878,621.818819,559.603231,556.103265,464.099504,412.977514,355.203227,379.564628,339.296459,Africa,8.390505e+06,215,Burundi
18,59.723,1.413186e+07,1713.778686,896.226015,734.285170,682.303175,683.895573,624.475478,524.972183,421.624026,523.432314,496.913648,434.038336,368.469286,Asia,1.413186e+07,227,Cambodia
19,54.985,1.769629e+07,2042.095240,1934.011449,1694.337469,1793.163278,2602.664206,2367.983282,1783.432873,1684.146528,1508.453148,1399.607441,1313.048099,1172.667655,Africa,1.769629e+07,239,Cameroon
20,80.653,3.339014e+07,36319.235010,33328.965070,28954.925890,26342.884260,26626.515030,22898.792140,22090.883060,18970.570860,16076.588030,13462.485550,12489.950060,11367.161120,Americas,3.339014e+07,251,Canada
21,50.485,4.369038e+06,706.016537,738.690607,740.506332,747.905525,844.876350,956.752991,1109.374338,1070.013275,1136.056615,1193.068753,1190.844328,1071.310713,Africa,4.369038e+06,263,Central African Republic
22,51.724,1.023881e+07,1704.063724,1156.181860,1004.961353,1058.064300,952.386129,797.908101,1133.984950,1104.103987,1196.810565,1389.817618,1308.495577,1178.665927,Africa,1.023881e+07,275,Chad
23,78.553,1.628474e+07,13171.638850,10778.783850,10118.053180,7596.125964,5547.063754,5095.665738,4756.763836,5494.024437,5106.654313,4519.094331,4315.622723,3939.978789,Americas,1.628474e+07,287,Chile
24,72.961,1.318683e+09,4959.114854,3119.280896,2289.234136,1655.784158,1378.904018,962.421380,741.237470,676.900092,612.705693,487.674018,575.987001,400.448611,Asia,1.318683e+09,299,China
25,72.889,4.422755e+07,7006.580419,5755.259962,6117.361746,5444.648617,4903.219100,4397.575659,3815.807870,3264.660041,2678.729839,2492.351109,2323.805581,2144.115096,Americas,4.422755e+07,311,Colombia
26,65.152,7.109600e+05,986.147879,1075.811558,1173.618235,1246.907370,1315.980812,1267.100083,1172.603047,1937.577675,1876.029643,1406.648278,1211.148548,1102.990936,Africa,7.109600e+05,323,Comoros
27,47.804,6.460676e+07,277.551859,241.165877,312.188423,457.719181,672.774812,673.747818,795.757282,904.896069,861.593242,896.314634,905.860230,780.542326,Africa,6.460676e+07,335,Congo Dem. Rep.
28,57.470,3.800610e+06,3632.557798,3484.061970,3484.164376,4016.239529,4201.194937,4879.507522,3259.178978,3213.152683,2677.939642,2464.783157,2315.056572,2125.621418,Africa,3.800610e+06,347,Congo Rep.
29,78.782,4.133884e+06,9645.061420,7723.447195,6677.045314,6160.416317,5629.915318,5262.734751,5926.876967,5118.146939,4161.727834,3460.937025,2990.010802,2627.009471,Americas,4.133884e+06,359,Costa Rica
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,42.568,6.144562e+06,862.540756,699.489713,574.648158,1068.696278,1294.447788,1465.010784,1348.285159,1353.759762,1206.043465,1116.639877,1004.484437,879.787736,Africa,6.144562e+06,1355,Sierra Leone
113,79.972,4.553009e+06,47143.179640,36023.105400,33519.476600,24769.891200,18861.530810,15169.161120,11210.089480,8597.756202,4977.418540,3674.735572,2843.104409,2315.138227,Asia,4.553009e+06,1367,Singapore
114,74.663,5.447502e+06,18678.314350,13638.778370,12126.230650,9498.467723,12037.267580,11348.545850,10922.664040,9674.167626,8412.902397,7481.107598,6093.262980,5074.659104,Europe,5.447502e+06,1379,Slovak Republic
115,77.926,2.011612e+06,25768.257590,20660.019360,17161.107350,14214.716810,18678.534920,17866.721750,15277.030170,12383.486200,9405.489397,7402.303395,5862.276629,4215.041741,Europe,2.011612e+06,1391,Slovenia
116,48.159,9.118773e+06,926.141068,882.081822,930.596428,926.960296,1093.244963,1176.807031,1450.992513,1254.576127,1284.733180,1369.488336,1258.147413,1135.749842,Africa,9.118773e+06,1403,Somalia
117,61.888,4.443362e+07,9269.657808,7710.946444,7479.188244,7225.069258,7825.823398,8568.266228,8028.651439,7765.962636,7114.477971,5768.729717,5487.104219,4725.295531,Africa,4.443362e+07,1415,South Africa
118,80.941,4.044819e+07,28821.063700,24835.471660,20445.298960,18603.064520,15764.983130,13926.169970,13236.921170,10638.751310,7993.512294,5693.843879,4564.802410,3834.034742,Europe,4.044819e+07,1427,Spain
119,72.396,2.037824e+07,3970.095407,3015.378833,2664.477257,2153.739222,1876.766827,1648.079789,1348.775651,1213.395530,1135.514326,1074.471960,1072.546602,1083.532030,Asia,2.037824e+07,1439,Sri Lanka
120,58.556,4.229293e+07,2602.394995,1993.398314,1632.210764,1492.197043,1507.819159,1895.544073,2202.988423,1659.652775,1687.997641,1959.593767,1770.337074,1615.991129,Africa,4.229293e+07,1451,Sudan
121,58.474,1.133066e+06,4513.480643,4128.116943,3876.768460,3553.022400,3984.839812,3895.384018,3781.410618,3364.836625,2613.101665,1856.182125,1244.708364,1148.376626,Africa,1.133066e+06,1463,Swaziland
122,80.884,9.031088e+06,33859.748350,29341.630930,25266.594990,23880.016830,23586.929270,20667.381250,18855.725210,17832.024640,15258.296970,12329.441920,9911.878226,8527.844662,Europe,9.031088e+06,1475,Sweden
123,81.701,7.554661e+06,37506.419070,34480.957710,32135.323010,31871.530300,30281.704590,28397.715120,26982.290520,27195.113040,22966.144320,20431.092700,17909.489730,14734.232750,Europe,7.554661e+06,1487,Switzerland
124,74.143,1.931475e+07,4184.548089,4090.925331,4014.238972,3340.542768,3116.774285,3761.837715,3195.484582,2571.423014,1881.923632,2193.037133,2117.234893,1643.485354,Asia,1.931475e+07,1499,Syria
125,78.400,2.317429e+07,28718.276840,23235.423290,20206.820980,15215.657900,11054.561750,7426.354774,5596.519826,4062.523897,2643.858681,1822.879028,1507.861290,1206.947913,Asia,2.317429e+07,1511,Taiwan
126,52.517,3.813964e+07,1107.482182,899.074211,789.186223,825.682454,831.822079,874.242607,962.492293,915.985059,848.218657,722.003807,698.535607,716.650072,Africa,3.813964e+07,1523,Tanzania
127,70.616,6.506815e+07,7458.396327,5913.187529,5852.625497,4616.896545,2982.653773,2393.219781,1961.224635,1524.358936,1295.460660,1002.199172,793.577415,757.797418,Asia,6.506815e+07,1535,Thailand
128,58.420,5.701579e+06,882.969944,886.220577,982.286924,1034.298904,1202.201361,1344.577953,1532.776998,1649.660188,1477.596760,1067.534810,925.908320,859.808657,Africa,5.701579e+06,1547,Togo
129,69.862,1.191336e+06,18008.509240,11460.600230,8792.573126,7370.990932,7388.597823,9119.528607,7899.554209,6619.551419,5621.368472,4997.523971,4100.393400,3023.271928,Americas,1.191336e+06,1559,Trinidad and Tobago
130,73.923,1.027616e+07,7092.923025,5722.895655,4876.798614,4332.720164,3810.419296,3560.233174,3120.876811,2753.285994,1932.360167,1660.303210,1395.232468,1468.475631,Africa,1.027616e+07,1571,Tunisia
131,71.777,7.115865e+07,8458.276384,6508.085718,6601.429915,5678.348271,5089.043686,4241.356344,4269.122326,3450.696380,2826.356387,2322.869908,2218.754257,1969.100980,Europe,7.115865e+07,1583,Turkey
132,51.542,2.917040e+07,1056.380121,927.721002,816.559081,644.170797,617.724406,682.266227,843.733137,950.735869,908.918522,767.271740,774.371069,734.753484,Africa,2.917040e+07,1595,Uganda
133,79.425,6.077624e+07,33203.261280,29478.999190,26074.531360,22705.092540,21664.787670,18232.424520,17428.748460,15895.116410,14142.850890,12477.177070,11283.177950,9979.508487,Europe,6.077624e+07,1607,United Kingdom
134,78.242,3.011399e+08,42951.653090,39097.099550,35767.433030,32003.932240,29884.350410,25009.559140,24072.632130,21806.035940,19530.365570,16173.145860,14847.127120,13990.482080,Americas,3.011399e+08,1619,United States
135,76.384,3.447496e+06,10611.462990,7727.002004,9230.240708,8137.004775,7452.398969,6920.223051,6504.339663,5703.408898,5444.619620,5603.357717,6150.772969,5716.766744,Americas,3.447496e+06,1631,Uruguay
136,73.747,2.608466e+07,11415.805690,8605.047831,10165.495180,10733.926310,9883.584648,11152.410110,13143.950950,10505.259660,9541.474188,8422.974165,9802.466526,7689.799761,Americas,2.608466e+07,1643,Venezuela
137,74.249,8.526236e+07,2441.576404,1764.456677,1385.896769,989.023149,820.799445,707.235786,713.537120,699.501644,637.123289,772.049160,676.285448,605.066492,Asia,8.526236e+07,1655,Vietnam
138,73.422,4.018332e+06,3025.349798,4515.487575,7110.667619,6017.654756,5107.197384,4336.032082,3682.831494,3133.409277,2649.715007,2198.956312,1827.067742,1515.592329,Asia,4.018332e+06,1667,West Bank and Gaza
139,62.698,2.221174e+07,2280.769906,2234.820827,2117.484526,1879.496673,1971.741538,1977.557010,1829.765177,1265.047031,862.442146,825.623201,804.830455,781.717576,Asia,2.221174e+07,1679,Yemen Rep.
140,51.821,1.174604e+07,1271.211593,1071.613938,1071.353818,1210.884633,1213.315116,1408.678565,1588.688299,1773.498265,1777.077318,1452.725766,1311.956766,1147.388831,Africa,1.174604e+07,1691,Zambia
141,62.351,1.231114e+07,469.709298,672.038623,792.449960,693.420786,706.157306,788.855041,685.587682,799.362176,569.795071,527.272182,518.764268,406.884115,Africa,1.231114e+07,1703,Zimbabwe

## Transposing tables

In many cases we may need to transpose the column and rows in a table.  Pandas allows us to to this easily with the `T` command.

In [48]:
# Print first three rows of the data frame
newDF.head(3)
# Transpose the dataframe and print the first three rows
newDF_trans = newDF.T
newDF_trans.head(3)

,0,1,2,3,4,5,6,7,8,9,...,132,133,134,135,136,137,138,139,140,141
lifeExp2007,43.828,76.423,72.301,42.731,75.32,81.235,79.829,75.635,64.062,79.441,...,51.542,79.425,78.242,76.384,73.747,74.249,73.422,62.698,51.821,62.351
pop2007,3.18899e+07,3.60052e+06,3.33332e+07,1.24205e+07,4.03019e+07,2.04342e+07,8.19978e+06,708573,1.50448e+08,1.03922e+07,...,2.91704e+07,6.07762e+07,3.0114e+08,3.4475e+06,2.60847e+07,8.52624e+07,4.01833e+06,2.22117e+07,1.1746e+07,1.23111e+07
gdpPercap_2007,974.58,5937.03,6223.37,4797.23,12779.4,34435.4,36126.5,29796,1391.25,33692.6,...,1056.38,33203.3,42951.7,10611.5,11415.8,2441.58,3025.35,2280.77,1271.21,469.709

---
## EXERCISE:
1. Read in a new data frame for the gapminder_Americas.csv file
2. Print the last last three columns of the data frame

In [73]:
df_amer = pd.read_csv('gapminder_Americas.csv', index_col = 'country')
#df_amer
len(df_amer.columns)
df_amer.columns

df_amer.loc[:, 'gdpPercap_2007':'lifeExp2007']

                     gdpPercap_2007      pop2007  lifeExp2007
country
Argentina              12779.379640   40301927.0       75.320
Bolivia                 3822.137084    9119152.0       65.554
Brazil                  9065.800825  190010647.0       72.390
Canada                 36319.235010   33390141.0       80.653
Chile                  13171.638850   16284741.0       78.553
Colombia                7006.580419   44227550.0       72.889
Costa Rica              9645.061420    4133884.0       78.782
Cuba                    8948.102923   11416987.0       78.273
Dominican Republic      6025.374752    9319622.0       72.235
Ecuador                 6873.262326   13755680.0       74.994
El Salvador             5728.353514    6939688.0       71.878
Guatemala               5186.050003   12572928.0       70.259
Haiti                   1201.637154    8502814.0       60.916
Honduras                3548.330846    7483763.0       70.198
Jamaica                 7320.880262    2780132.0       72.567
Mexico                 11977.574960  108700891.0       76.195
Nicaragua               2749.320965    5675356.0       72.899
Panama                  9809.185636    3242173.0       75.537
Paraguay                4172.838464    6667147.0       71.752
Peru                    7408.905561   28674757.0       71.421
Puerto Rico            19328.709010    3942491.0       78.746
Trinidad and Tobago    18008.509240    1191336.0       69.862
United States          42951.653090  301139947.0       78.242
Uruguay                10611.462990    3447496.0       76.384
Venezuela              11415.805690   26084662.0       73.747

---
## Selecting values

Data Frames provides a index as a way to identify the rows of the table. A row also has a position inside the table as well as a label, which uniquely identifies its entry in the DataFrame.

To access a value at the position [ i , j ] (row, column) of a Data Frame, we have two options, depending on what is the meaning of i in use.

### Use DataFrame.iloc[..., ...] to select values by their position
* Allows you to specify location by numerical index similar to 2D version of character selection in strings.

In [61]:
print("\nData value in first row at first column: ", df.iloc[0, 0])

Data value in first row at first column:  0

In [62]:
print("\nData value in fifth row at third column: ", df.iloc[4, 2])

Data value in fifth row at third column:  1957

### Use `DataFrame.loc[..., ...]` to select values by their (index) label.

*   Can specify location by name or by numerical index.

In [82]:
# Print the value of Albanias GDP per capita in 1952 using .loc
df_all = pd.read_csv('gapminder_All.csv', index_col='country')
print(df_all.loc['Albania','gdpPercap_1952'])
#df_all

1601.056136

In [83]:
# Print the value of Bulgarias GDP per capita in 1962 using .loc
print(df_all.loc['Bulgaria','gdpPercap_1962'])

4254.337839

---
## EXERCISE
~~~
import pandas
df = pandas.read_csv('data/gapminder_Europe.csv', index_col='country')
~~~

1. Find the Per Capita GDP for Serbia in 2007.
1. Find the Per Capita GDPs for Germany in 1982

In [90]:
# Write your code here
import pandas as pd

df_euro = pd.read_csv('gapminder_Europe.csv', index_col = 'country')
print('Serbia\'s GDP in 2007 was: '+ str(df_euro.loc['Serbia','gdpPercap_2007']))
print('Germany\'s GDP in 1982 was:', df_euro.loc['Germany','gdpPercap_1982']) #this print auto adds space

Serbia's GDP in 2007 was: 9786.534714
Germany's GDP in 1982 was: 22031.532740000002

---
## Slicing Data Frames

### Use `:` on its own to mean all columns or all rows.

*   Just like Python's usual slicing notation, we can print all columns or all rows with `.loc` using the `:`

In [102]:
# Print all of the row values for all years for Egypt
import pandas as pd
df_all3 = pd.read_csv('gapminder_All.csv', index_col='country')
df_all3.loc['Egypt',:]

Unnamed: 0                467
pop               8.02645e+07
continent              Africa
gdpPercap_1952        1418.82
gdpPercap_1957        1458.92
gdpPercap_1962        1693.34
gdpPercap_1967        1814.88
gdpPercap_1972        2024.01
gdpPercap_1977        2785.49
gdpPercap_1982        3503.73
gdpPercap_1987        3885.46
gdpPercap_1992        3794.76
gdpPercap_1997        4173.18
gdpPercap_2002         4754.6
gdpPercap_2007        5581.18
pop2007           8.02645e+07
lifeExp2007            71.338
Name: Egypt, dtype: object

* Would get the same result printing `df.iloc[0]` (without a second index).
* We can also omit the `:` and get all rows.
    * e.g. `df.loc["Albania"]`

In [99]:
df_all3.iloc[0]

Unnamed: 0                 11
pop               3.18899e+07
continent                Asia
gdpPercap_1952        779.445
gdpPercap_1957        820.853
gdpPercap_1962        853.101
gdpPercap_1967        836.197
gdpPercap_1972        739.981
gdpPercap_1977        786.113
gdpPercap_1982        978.011
gdpPercap_1987        852.396
gdpPercap_1992        649.341
gdpPercap_1997        635.341
gdpPercap_2002        726.734
gdpPercap_2007         974.58
pop2007           3.18899e+07
lifeExp2007            43.828
Name: Afghanistan, dtype: object

In [106]:
# Print the GDP per capita for all countries in 1952
df_all3 = pd.read_csv('gapminder_All.csv',index_col='country')
df_all3.loc[:,'gdpPercap_1952']

country
Afghanistan                   779.445314
Albania                      1601.056136
Algeria                      2449.008185
Angola                       3520.610273
Argentina                    5911.315053
Australia                   10039.595640
Austria                      6137.076492
Bahrain                      9867.084765
Bangladesh                    684.244172
Belgium                      8343.105127
Benin                        1062.752200
Bolivia                      2677.326347
Bosnia and Herzegovina        973.533195
Botswana                      851.241141
Brazil                       2108.944355
Bulgaria                     2444.286648
Burkina Faso                  543.255241
Burundi                       339.296459
Cambodia                      368.469286
Cameroon                     1172.667655
Canada                      11367.161120
Central African Republic     1071.310713
Chad                         1178.665927
Chile                        3939.978789
China                         400.448611
Colombia                     2144.115096
Comoros                      1102.990936
Congo Dem. Rep.               780.542326
Congo Rep.                   2125.621418
Costa Rica                   2627.009471
                                ...
Sierra Leone                  879.787736
Singapore                    2315.138227
Slovak Republic              5074.659104
Slovenia                     4215.041741
Somalia                      1135.749842
South Africa                 4725.295531
Spain                        3834.034742
Sri Lanka                    1083.532030
Sudan                        1615.991129
Swaziland                    1148.376626
Sweden                       8527.844662
Switzerland                 14734.232750
Syria                        1643.485354
Taiwan                       1206.947913
Tanzania                      716.650072
Thailand                      757.797418
Togo                          859.808657
Trinidad and Tobago          3023.271928
Tunisia                      1468.475631
Turkey                       1969.100980
Uganda                        734.753484
United Kingdom               9979.508487
United States               13990.482080
Uruguay                      5716.766744
Venezuela                    7689.799761
Vietnam                       605.066492
West Bank and Gaza           1515.592329
Yemen Rep.                    781.717576
Zambia                       1147.388831
Zimbabwe                      406.884115
Name: gdpPercap_1952, Length: 142, dtype: float64

*   Would get the same result printing `df["gdpPercap_1952"]`
*   Also get the same result printing `df.gdpPercap_1952` (since it's a column name)

In [108]:
#df_all3['gdpPercap_1952']
df_all3.gdpPercap_1952

country
Afghanistan                   779.445314
Albania                      1601.056136
Algeria                      2449.008185
Angola                       3520.610273
Argentina                    5911.315053
Australia                   10039.595640
Austria                      6137.076492
Bahrain                      9867.084765
Bangladesh                    684.244172
Belgium                      8343.105127
Benin                        1062.752200
Bolivia                      2677.326347
Bosnia and Herzegovina        973.533195
Botswana                      851.241141
Brazil                       2108.944355
Bulgaria                     2444.286648
Burkina Faso                  543.255241
Burundi                       339.296459
Cambodia                      368.469286
Cameroon                     1172.667655
Canada                      11367.161120
Central African Republic     1071.310713
Chad                         1178.665927
Chile                        3939.978789
China                         400.448611
Colombia                     2144.115096
Comoros                      1102.990936
Congo Dem. Rep.               780.542326
Congo Rep.                   2125.621418
Costa Rica                   2627.009471
                                ...
Sierra Leone                  879.787736
Singapore                    2315.138227
Slovak Republic              5074.659104
Slovenia                     4215.041741
Somalia                      1135.749842
South Africa                 4725.295531
Spain                        3834.034742
Sri Lanka                    1083.532030
Sudan                        1615.991129
Swaziland                    1148.376626
Sweden                       8527.844662
Switzerland                 14734.232750
Syria                        1643.485354
Taiwan                       1206.947913
Tanzania                      716.650072
Thailand                      757.797418
Togo                          859.808657
Trinidad and Tobago          3023.271928
Tunisia                      1468.475631
Turkey                       1969.100980
Uganda                        734.753484
United Kingdom               9979.508487
United States               13990.482080
Uruguay                      5716.766744
Venezuela                    7689.799761
Vietnam                       605.066492
West Bank and Gaza           1515.592329
Yemen Rep.                    781.717576
Zambia                       1147.388831
Zimbabwe                      406.884115
Name: gdpPercap_1952, Length: 142, dtype: float64

---
## EXERCISE:
1. Print out GDP per capita for all countries in asia in 1972

In [109]:
# Write your code here
df_asia = pd.read_csv('gapminder_Asia.csv',index_col='country')
df_asia.gdpPercap_1972

country
Afghanistan              739.981106
Bahrain                18268.658390
Bangladesh               630.233627
Cambodia                 421.624026
China                    676.900092
Hong Kong China         8315.928145
India                    724.032527
Indonesia               1111.107907
Iran                    9613.818607
Iraq                    9576.037596
Israel                 12786.932230
Japan                  14778.786360
Jordan                  2110.856309
Korea Dem. Rep.         3701.621503
Korea Rep.              3030.876650
Kuwait                109347.867000
Lebanon                 7486.384341
Malaysia                2849.094780
Mongolia                1421.741975
Myanmar                  357.000000
Nepal                    674.788130
Oman                   10618.038550
Pakistan                1049.938981
Philippines             1989.374070
Saudi Arabia           24837.428650
Singapore               8597.756202
Sri Lanka               1213.395530
Syria                   2571.423014
Taiwan                  4062.523897
Thailand                1524.358936
Vietnam                  699.501644
West Bank and Gaza      3133.409277
Yemen Rep.              1265.047031
Name: gdpPercap_1972, dtype: float64

---
### We can also use the `:` to select whole sections of a table 
* Similar to the way we would select a section of from a normal python list, we can do the same with data frames.

In [110]:
# Print a selection of all countries in the table from Italy to Poland from years 1962 to 1972
df_all3.loc['Italy':'Poland']

,Unnamed: 0,pop,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007,pop2007,lifeExp2007
country,,,,,,,,,,,,,,,,,
Italy,779,58147733.0,Europe,4931.404155,6248.656232,8243.582340,10022.401310,12269.273780,14255.984750,16537.483500,19207.234820,22013.644860,24675.024460,27968.098170,28569.719700,58147733.0,80.546
Jamaica,791,2780132.0,Americas,2898.530881,4756.525781,5246.107524,6124.703451,7433.889293,6650.195573,6068.051350,6351.237495,7404.923685,7121.924704,6994.774861,7320.880262,2780132.0,72.567
Japan,803,127467972.0,Asia,3216.956347,4317.694365,6576.649461,9847.788607,14778.786360,16610.377010,19384.105710,22375.941890,26824.895110,28816.584990,28604.591900,31656.068060,127467972.0,82.603
Jordan,815,6053193.0,Asia,1546.907807,1886.080591,2348.009158,2741.796252,2110.856309,2852.351568,4161.415959,4448.679912,3431.593647,3645.379572,3844.917194,4519.461171,6053193.0,72.535
Kenya,827,35610177.0,Africa,853.540919,944.438315,896.966373,1056.736457,1222.359968,1267.613204,1348.225791,1361.936856,1341.921721,1360.485021,1287.514732,1463.249282,35610177.0,59.339
Korea Dem. Rep.,839,23301725.0,Asia,1088.277758,1571.134655,1621.693598,2143.540609,3701.621503,4106.301249,4106.525293,4106.492315,3726.063507,1690.756814,1646.758151,1593.065480,23301725.0,70.647
Korea Rep.,851,49044790.0,Asia,1030.592226,1487.593537,1536.344387,2029.228142,3030.876650,4657.221020,5622.942464,8533.088805,12104.278720,15993.527960,19233.988180,23348.139730,49044790.0,78.623
Kuwait,863,2505559.0,Asia,108382.352900,113523.132900,95458.111760,80894.883260,109347.867000,59265.477140,31354.035730,28118.429980,34932.919590,40300.619960,35110.105660,47306.989780,2505559.0,77.588
Lebanon,875,3921278.0,Asia,4834.804067,6089.786934,5714.560611,6006.983042,7486.384341,8659.696836,7640.519521,5377.091329,6890.806854,8754.963850,9313.938830,10461.058680,3921278.0,71.993
Lesotho,887,2046772.0,Africa,298.846212,335.997115,411.800627,498.639026,496.581592,745.369541,797.263107,773.993214,977.486272,1186.147994,1275.184575,1569.331442,2046772.0,59.685
Liberia,899,3193942.0,Africa,575.572996,620.969990,634.195163,713.603648,803.005454,640.322438,572.199569,506.113857,636.622919,609.173951,531.482368,414.507341,3193942.0,46.027
Libya,911,6036914.0,Africa,2387.548060,3448.284395,6757.030816,18772.751690,21011.497210,21951.211760,17364.275380,11770.589800,9640.138501,9467.446056,9534.677467,12057.499280,6036914.0,73.952
Madagascar,923,19167654.0,Africa,1443.011715,1589.202750,1643.387110,1634.047282,1748.562982,1544.228586,1302.878658,1155.441948,1040.676190,986.295896,894.637082,1044.770126,19167654.0,59.443
Malawi,935,13327079.0,Africa,369.165080,416.369806,427.901086,495.514781,584.621971,663.223677,632.803921,635.517363,563.200014,692.275810,665.423119,759.349910,13327079.0,49.420
Malaysia,947,24821286.0,Asia,1831.132894,1810.066992,2036.884944,2277.742396,2849.094780,3827.921571,4920.355951,5249.802653,7277.912802,10132.909640,10206.977940,12451.655800,24821286.0,74.241
Mali,959,12031795.0,Africa,452.336981,490.382187,496.174343,545.009887,581.368876,686.395269,618.014064,684.171558,739.014375,790.257985,951.409752,1042.581557,12031795.0,54.467
Mauritania,971,3270065.0,Africa,743.115910,846.120261,1055.896036,1421.145193,1586.851781,1497.492223,1481.150189,1421.603576,1361.369784,1483.136136,1579.019543,1803.151496,3270065.0,64.164
Mauritius,983,1250882.0,Africa,1967.955707,2034.037981,2529.067487,2475.387562,2575.484158,3710.982963,3688.037739,4783.586903,6058.253846,7425.705295,9021.815894,10956.991120,1250882.0,72.801
Mexico,995,108700891.0,Americas,3478.125529,4131.546641,4581.609385,5754.733883,6809.406690,7674.929108,9611.147541,8688.156003,9472.384295,9767.297530,10742.440530,11977.574960,108700891.0,76.195
Mongolia,1007,2874127.0,Asia,786.566857,912.662609,1056.353958,1226.041130,1421.741975,1647.511665,2000.603139,2338.008304,1785.402016,1902.252100,2140.739323,3095.772271,2874127.0,66.803
Montenegro,1019,720230.0,Europe,2647.585601,3682.259903,4649.593785,5907.850937,7778.414017,9595.929905,11222.587620,11732.510170,7003.339037,6465.613349,6557.194282,9253.896111,720230.0,75.445
Morocco,1031,33757175.0,Africa,1688.203570,1642.002314,1566.353493,1711.044770,1930.194975,2370.619976,2702.620356,2755.046991,2948.047252,2982.101858,3258.495584,3820.175230,33757175.0,71.164
Mozambique,1043,19951656.0,Africa,468.526038,495.586833,556.686354,566.669154,724.917804,502.319733,462.211415,389.876185,410.896824,472.346077,633.617947,823.685621,19951656.0,46.344
Myanmar,1055,47761980.0,Asia,331.000000,350.000000,388.000000,349.000000,357.000000,371.000000,424.000000,385.000000,347.000000,415.000000,611.000000,944.000000,47761980.0,62.069
Namibia,1067,2055080.0,Africa,2423.780443,2621.448058,3173.215595,3793.694753,3746.080948,3876.485958,4191.100511,3693.731337,3804.537999,3899.524260,4072.324751,4811.060429,2055080.0,61.999
Nepal,1079,28901790.0,Asia,545.865723,597.936356,652.396859,676.442225,674.788130,694.112440,718.373095,775.632450,897.740360,1010.892138,1057.206311,1091.359778,28901790.0,63.785
Netherlands,1091,16570613.0,Europe,8941.571858,11276.193440,12790.849560,15363.251360,18794.745670,21209.059200,21399.460460,23651.323610,26790.949610,30246.130630,33724.757780,36797.933320,16570613.0,79.762
New Zealand,1103,4115771.0,Oceania,10556.575660,12247.395320,13175.678000,14463.918930,16046.037280,16233.717700,17632.410400,19007.191290,18363.324940,21050.413770,23189.801350,25185.009110,4115771.0,80.204
Nicaragua,1115,5675356.0,Americas,3112.363948,3457.415947,3634.364406,4643.393534,4688.593267,5486.371089,3470.338156,2955.984375,2170.151724,2253.023004,2474.548819,2749.320965,5675356.0,72.899
Niger,1127,12894865.0,Africa,761.879376,835.523403,997.766113,1054.384891,954.209236,808.897073,909.722135,668.300023,581.182725,580.305209,601.074501,619.676892,12894865.0,56.867
Nigeria,1139,135031164.0,Africa,1077.281856,1100.592563,1150.927478,1014.514104,1698.388838,1981.951806,1576.973750,1385.029563,1619.848217,1624.941275,1615.286395,2013.977305,135031164.0,47.472
Norway,1151,4627926.0,Europe,10095.421720,11653.973040,13450.401510,16361.876470,18965.055510,23311.349390,26298.635310,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170,4627926.0,80.196
Oman,1163,3204897.0,Asia,1828.230307,2242.746551,2924.638113,4720.942687,10618.038550,11848.343920,12954.791010,18115.223130,18616.706910,19702.055810,19774.836870,22316.192870,3204897.0,75.640
Pakistan,1175,169270617.0,Asia,684.597144,747.083529,803.342742,942.408259,1049.938981,1175.921193,1443.429832,1704.686583,1971.829464,2049.350521,2092.712441,2605.947580,169270617.0,65.483
Panama,1187,3242173.0,Americas,2480.380334,2961.800905,3536.540301,4421.009084,5364.249663,5351.912144,7009.601598,7034.779161,6618.743050,7113.692252,7356.031934,9809.185636,3242173.0,75.537
Paraguay,1199,6667147.0,Americas,1952.308701,2046.154706,2148.027146,2299.376311,2523.337977,3248.373311,4258.503604,3998.875695,4196.411078,4247.400261,3783.674243,4172.838464,6667147.0,71.752
Peru,1211,28674757.0,Americas,3758.523437,4245.256698,4957.037982,5788.093330,5937.827283,6281.290855,6434.501797,6360.943444,4446.380924,5838.347657,5909.020073,7408.905561,28674757.0,71.421
Philippines,1223,91077287.0,Asia,1272.880995,1547.944844,1649.552153,1814.127430,1989.374070,2373.204287,2603.273765,2189.634995,2279.324017,2536.534925,2650.921068,3190.481016,91077287.0,71.688
Poland,1235,38654957.0,Europe,4029.329699,4734.253019,5338.752143,6557.152776,8006.506993,9508.141454,8451.531004,9082.351172,7738.881247,10159.583680,12002.239080,15389.924680,38654957.0,75.563

Note that in Pandas **slicing using indexes is inclusive at both ends**, which differs from typical python behavior where slicing indicates everything up to but not including the final index.

### Select multiple columns or rows using `DataFrame.iloc` and a named slice.
* We can also make selection from a data frame using the index location of the row or column
    * Remember that in programming languages, we start counting at 0

In [122]:
#Print the first row of the data frame using the .head() function
print("First row of data frame:\n", df_all3.head(1) )

# Use iloc to print the value in the first row of the first column
print("\n\nValue in the first row of the first column:\n", df_all3.iloc[0,0] )

# Use iloc to print the values of the first two columns in the first row
print("Values in the first two columes in the first row:\n", df_all3.iloc[0,0:2] )

First row of data frame:
              Unnamed: 0         pop continent  gdpPercap_1952  gdpPercap_1957  \
country
Afghanistan          11  31889923.0      Asia      779.445314       820.85303

             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  \
country
Afghanistan       853.10071      836.197138      739.981106       786.11336

             gdpPercap_1982  gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  \
country
Afghanistan      978.011439      852.395945      649.341395      635.341351

             gdpPercap_2002  gdpPercap_2007     pop2007  lifeExp2007
country
Afghanistan      726.734055      974.580338  31889923.0       43.828


Value in the first row of the first column:
 11
Values in the first two columes in the first row:
 Unnamed: 0             11
pop           3.18899e+07
Name: Afghanistan, dtype: object

* **Note that unlike slicing using column or row names, slicing using indexes is not inclusive**

---
## EXERCISE:
1. Print out all values from Hungary through Montenegro (Europe data) for the years 1977 through 1997

In [124]:
# Write code here
df_euro.loc['Hungary':'Montenego','gdpPercap_1977':'gdpPercap_1997']

,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997
country,,,,,
Hungary,11674.83737,12545.99066,12986.47998,10535.62855,11712.77680
Iceland,19654.96247,23269.60750,26923.20628,25144.39201,28061.09966
Ireland,11150.98113,12618.32141,13872.86652,17558.81555,24521.94713
Italy,14255.98475,16537.48350,19207.23482,22013.64486,24675.02446

---
## EXERCISE:
1.  Do the two statements below produce the same output?
    ~~~
    print(df.iloc[0:2, 0:2])
    print(df.loc['Albania':'Belgium', 'gdpPercap_1952':'gdpPercap_1962'])
    ~~~

1.  Based on this,what rule governs what is included (or not) in numerical slices and named slices in Pandas?

In [126]:
print(df_all3.iloc[0:2, 0:2])
print('\nnext one coming\n')
print(df_all3.loc['Albania':'Belgium', 'gdpPercap_1952':'gdpPercap_1962'])

             Unnamed: 0         pop
country
Afghanistan          11  31889923.0
Albania              23   3600523.0

next one coming

            gdpPercap_1952  gdpPercap_1957  gdpPercap_1962
country
Albania        1601.056136     1942.284244     2312.888958
Algeria        2449.008185     3013.976023     2550.816880
Angola         3520.610273     3827.940465     4269.276742
Argentina      5911.315053     6856.856212     7133.166023
Australia     10039.595640    10949.649590    12217.226860
Austria        6137.076492     8842.598030    10750.721110
Bahrain        9867.084765    11635.799450    12753.275140
Bangladesh      684.244172      661.637458      686.341554
Belgium        8343.105127     9714.960623    10991.206760

---
### Slicing individual rows and columns
* Instead of creating slices of *this* to *that* using the `:`, we can also slice using individual rows and columns by placing names or indexes in brackets `[]`.

In [127]:
# Print out the GDP per capita of only Italy, Austria, and the United Kingdom in the years 2007 and 1957
df_euro.loc[['Italy','Austria','United Kingdom'],['gdpPercap_1957','gdpPercap_2007']]

                gdpPercap_1957  gdpPercap_2007
country
Italy              6248.656232     28569.71970
Austria            8842.598030     36126.49270
United Kingdom    11283.177950     33203.26128

---
## EXERCISE:
1. Using the index locations, `print` out the first, third, and eight columns for the sixteenth through nineteenth rows.

In [131]:
print(df_euro.iloc[[15,16,17,18],[0,2,7]])

             Unnamed: 0 continent  gdpPercap_1972
country
Italy               779    Europe    12269.273780
Montenegro         1019    Europe     7778.414017
Netherlands        1091    Europe    18794.745670
Norway             1151    Europe    18965.055510

---
## Result of slicing can be used in further operations.

In [135]:
# Print out the max value (.max()) of ALL countries from Italy to Poland for 1962 to 1972
print(df_euro.loc['Italy':'Poland','gdpPercap_1962':'gdpPercap_1972'])
print('\nNext One\n')
print(df_euro.loc['Italy':'Poland','gdpPercap_1962':'gdpPercap_1972'].max())

             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Italy           8243.582340    10022.401310    12269.273780
Montenegro      4649.593785     5907.850937     7778.414017
Netherlands    12790.849560    15363.251360    18794.745670
Norway         13450.401510    16361.876470    18965.055510
Poland          5338.752143     6557.152776     8006.506993

Next One

gdpPercap_1962    13450.40151
gdpPercap_1967    16361.87647
gdpPercap_1972    18965.05551
dtype: float64

In [136]:
# Print out the min value (.min()) of ALL countries from Italy to Poland for 1962 to 1972
print(df_euro.loc['Italy':'Poland','gdpPercap_1962':'gdpPercap_1972'])
print('\nNext One\n')
print(df_euro.loc['Italy':'Poland','gdpPercap_1962':'gdpPercap_1972'].min())

             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Italy           8243.582340    10022.401310    12269.273780
Montenegro      4649.593785     5907.850937     7778.414017
Netherlands    12790.849560    15363.251360    18794.745670
Norway         13450.401510    16361.876470    18965.055510
Poland          5338.752143     6557.152776     8006.506993

Next One

gdpPercap_1962    4649.593785
gdpPercap_1967    5907.850937
gdpPercap_1972    7778.414017
dtype: float64

*   Usually don't just print a slice.
*   All the statistical operators that work on entire data frames work the same way on slices.

## Create data frame from selections

* We can create new data frame by selecting data frames based on values and assigining it to a variable

In [137]:
# Create a selection of ALL countries from Italy to Poland for 1962 to 1972 and 
#  assign the selection to a variable name "subset_df"
subset_df = df_euro.loc['Italy':'Poland','gdpPercap_1962':'gdpPercap_1972']

print('Subset of data:\n', subset_df)

Subset of data:
              gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Italy           8243.582340    10022.401310    12269.273780
Montenegro      4649.593785     5907.850937     7778.414017
Netherlands    12790.849560    15363.251360    18794.745670
Norway         13450.401510    16361.876470    18965.055510
Poland          5338.752143     6557.152776     8006.506993

## Create DataFrame using query
* We can query values in a data frame to create new selections
* By passing a dataframe query to itself, we can create a new dataframe with only those values

In [157]:
# Create a query for the "gdpPerCap_1962" series in out subset_df data frame for all values greater than 10000

# Create a new data frame called subset_10k_df by passing that query to the subset_df data frame

query_10k = subset_df[subset_df.gdpPercap_1962>10000]
print(query_10k)
subset_10k_df = pd.DataFrame(query_10k)
print(subset_10k_df)
print(subset_10k_df.shape)

             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Netherlands     12790.84956     15363.25136     18794.74567
Norway          13450.40151     16361.87647     18965.05551
             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Netherlands     12790.84956     15363.25136     18794.74567
Norway          13450.40151     16361.87647     18965.05551
(2, 3)

---
## EXERCISE:

* Create three data frames and get the size of each one.
    1. Countries with a gdp per capita in 1952 above 10000
    1. Countries with a gdp per capita in 1962 above 10000
    1. Countries with a gdp per capita in 1972 above 10000

---

In [166]:
subset_1952_72 = df_all3.loc[:,['gdpPercap_1952','gdpPercap_1962','gdpPercap_1972']]
print(subset_1952_72)
q1952_10k = subset_1952_72[subset_1952_72.gdpPercap_1952>10000]
subset_10k_1952 = pd.DataFrame(q1952_10k)
print(subset_10k_1952)
print(subset_10k_1952.shape, "is the size of the new 1952 dataframe")

q1962_10k = subset_1952_72[subset_1952_72.gdpPercap_1962>10000]
subset_10k_1962 = pd.DataFrame(q1962_10k)
print(subset_10k_1962)
print(subset_10k_1962.shape, "is the size of the new 1962 dataframe")

q1972_10k = subset_1952_72[subset_1952_72.gdpPercap_1972>10000]
subset_10k_1972 = pd.DataFrame(q1972_10k)
print(subset_10k_1972)
print(subset_10k_1972.shape, "is the size of the new 1972 dataframe")

                          gdpPercap_1952  gdpPercap_1962  gdpPercap_1972
country
Afghanistan                   779.445314      853.100710      739.981106
Albania                      1601.056136     2312.888958     3313.422188
Algeria                      2449.008185     2550.816880     4182.663766
Angola                       3520.610273     4269.276742     5473.288005
Argentina                    5911.315053     7133.166023     9443.038526
Australia                   10039.595640    12217.226860    16788.629480
Austria                      6137.076492    10750.721110    16661.625600
Bahrain                      9867.084765    12753.275140    18268.658390
Bangladesh                    684.244172      686.341554      630.233627
Belgium                      8343.105127    10991.206760    16672.143560
Benin                        1062.752200      949.499064     1085.796879
Bolivia                      2677.326347     2180.972546     2980.331339
Bosnia and Herzegovina        973.533195     1709.683679     2860.169750
Botswana                      851.241141      983.653976     2263.611114
Brazil                       2108.944355     3336.585802     4985.711467
Bulgaria                     2444.286648     4254.337839     6597.494398
Burkina Faso                  543.255241      722.512021      854.735976
Burundi                       339.296459      355.203227      464.099504
Cambodia                      368.469286      496.913648      421.624026
Cameroon                     1172.667655     1399.607441     1684.146528
Canada                      11367.161120    13462.485550    18970.570860
Central African Republic     1071.310713     1193.068753     1070.013275
Chad                         1178.665927     1389.817618     1104.103987
Chile                        3939.978789     4519.094331     5494.024437
China                         400.448611      487.674018      676.900092
Colombia                     2144.115096     2492.351109     3264.660041
Comoros                      1102.990936     1406.648278     1937.577675
Congo Dem. Rep.               780.542326      896.314634      904.896069
Congo Rep.                   2125.621418     2464.783157     3213.152683
Costa Rica                   2627.009471     3460.937025     5118.146939
...                                  ...             ...             ...
Sierra Leone                  879.787736     1116.639877     1353.759762
Singapore                    2315.138227     3674.735572     8597.756202
Slovak Republic              5074.659104     7481.107598     9674.167626
Slovenia                     4215.041741     7402.303395    12383.486200
Somalia                      1135.749842     1369.488336     1254.576127
South Africa                 4725.295531     5768.729717     7765.962636
Spain                        3834.034742     5693.843879    10638.751310
Sri Lanka                    1083.532030     1074.471960     1213.395530
Sudan                        1615.991129     1959.593767     1659.652775
Swaziland                    1148.376626     1856.182125     3364.836625
Sweden                       8527.844662    12329.441920    17832.024640
Switzerland                 14734.232750    20431.092700    27195.113040
Syria                        1643.485354     2193.037133     2571.423014
Taiwan                       1206.947913     1822.879028     4062.523897
Tanzania                      716.650072      722.003807      915.985059
Thailand                      757.797418     1002.199172     1524.358936
Togo                          859.808657     1067.534810     1649.660188
Trinidad and Tobago          3023.271928     4997.523971     6619.551419
Tunisia                      1468.475631     1660.303210     2753.285994
Turkey                       1969.100980     2322.869908     3450.696380
Uganda                        734.753484      767.271740      950.735869
United Kingdom               9979.508487    12477.177070    15895.116410
United States               13990.482080    16173.145860    21806.035940
Uruguay                      5716.766744     5603.357717     5703.408898
Venezuela                    7689.799761     8422.974165    10505.259660
Vietnam                       605.066492      772.049160      699.501644
West Bank and Gaza           1515.592329     2198.956312     3133.409277
Yemen Rep.                    781.717576      825.623201     1265.047031
Zambia                       1147.388831     1452.725766     1773.498265
Zimbabwe                      406.884115      527.272182      799.362176

[142 rows x 3 columns]
               gdpPercap_1952  gdpPercap_1962  gdpPercap_1972
country
Australia         10039.59564     12217.22686     16788.62948
Canada            11367.16112     13462.48555     18970.57086
Kuwait           108382.35290     95458.11176    109347.86700
New Zealand       10556.57566     13175.67800     16046.03728
Norway            10095.42172     13450.40151     18965.05551
Switzerland       14734.23275     20431.09270     27195.11304
United States     13990.48208     16173.14586     21806.03594
(7, 3) is the size of the new 1952 dataframe
                gdpPercap_1952  gdpPercap_1962  gdpPercap_1972
country
Australia         10039.595640     12217.22686     16788.62948
Austria            6137.076492     10750.72111     16661.62560
Bahrain            9867.084765     12753.27514     18268.65839
Belgium            8343.105127     10991.20676     16672.14356
Canada            11367.161120     13462.48555     18970.57086
Czech Republic     6876.140250     10136.86713     13108.45360
Denmark            9692.385245     13583.31351     18866.20721
France             7029.809327     10560.48553     16107.19171
Germany            7144.114393     12902.46291     18016.18027
Iceland            7267.688428     10350.15906     15798.06362
Kuwait           108382.352900     95458.11176    109347.86700
Netherlands        8941.571858     12790.84956     18794.74567
New Zealand       10556.575660     13175.67800     16046.03728
Norway            10095.421720     13450.40151     18965.05551
Saudi Arabia       6459.554823     11626.41975     24837.42865
Sweden             8527.844662     12329.44192     17832.02464
Switzerland       14734.232750     20431.09270     27195.11304
United Kingdom     9979.508487     12477.17707     15895.11641
United States     13990.482080     16173.14586     21806.03594
(19, 3) is the size of the new 1962 dataframe
                gdpPercap_1952  gdpPercap_1962  gdpPercap_1972
country
Australia         10039.595640    12217.226860     16788.62948
Austria            6137.076492    10750.721110     16661.62560
Bahrain            9867.084765    12753.275140     18268.65839
Belgium            8343.105127    10991.206760     16672.14356
Canada            11367.161120    13462.485550     18970.57086
Czech Republic     6876.140250    10136.867130     13108.45360
Denmark            9692.385245    13583.313510     18866.20721
Finland            6424.519071     9371.842561     14358.87590
France             7029.809327    10560.485530     16107.19171
Gabon              4293.476475     6631.459222     11401.94841
Germany            7144.114393    12902.462910     18016.18027
Greece             3530.690067     6017.190733     12724.82957
Hungary            5263.673816     7550.359877     10168.65611
Iceland            7267.688428    10350.159060     15798.06362
Israel             4086.522128     7105.630706     12786.93223
Italy              4931.404155     8243.582340     12269.27378
Japan              3216.956347     6576.649461     14778.78636
Kuwait           108382.352900    95458.111760    109347.86700
Libya              2387.548060     6757.030816     21011.49721
Netherlands        8941.571858    12790.849560     18794.74567
New Zealand       10556.575660    13175.678000     16046.03728
Norway            10095.421720    13450.401510     18965.05551
Oman               1828.230307     2924.638113     10618.03855
Saudi Arabia       6459.554823    11626.419750     24837.42865
Serbia             3581.459448     6289.629157     10522.06749
Slovenia           4215.041741     7402.303395     12383.48620
Spain              3834.034742     5693.843879     10638.75131
Sweden             8527.844662    12329.441920     17832.02464
Switzerland       14734.232750    20431.092700     27195.11304
United Kingdom     9979.508487    12477.177070     15895.11641
United States     13990.482080    16173.145860     21806.03594
Venezuela          7689.799761     8422.974165     10505.25966
(32, 3) is the size of the new 1972 dataframe

## Filter a DataFrame using a Boolean mask

* A frame full of Booleans is sometimes called a *mask* because of how it can be used
* Comparison is applied element by element
* Returns a similarly-shaped data frame of `True` and `False`

In [168]:
# Create a full data frame mask for subset_df with a query for all values in all years greater than 10000
mask_10k = subset_df>10000

print( mask_10k )

             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Italy                 False            True            True
Montenegro            False           False           False
Netherlands            True            True            True
Norway                 True            True            True
Poland                False           False           False

* We can use masks to filter an entire dataframe with a single query
    * More efficient than using a single query on multiple columns

In [172]:
# Pass the mask query to subset_df to create a new data frame mask_subset
mask_subset = subset_df[mask_10k]

print(mask_subset)
print("Shape: ", mask_subset.shape)

             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Italy                   NaN     10022.40131     12269.27378
Montenegro              NaN             NaN             NaN
Netherlands     12790.84956     15363.25136     18794.74567
Norway          13450.40151     16361.87647     18965.05551
Poland                  NaN             NaN             NaN
Shape:  (5, 3)

*   Returns the value where the mask is true, and NaN (Not a Number) where it is false.
*   Useful because NaNs are ignored by operations like max, min, average, etc.


* If we wanted to remove all rows with a NaN value in any column we could use the `.dropna()` function

In [174]:
# Print the mask_subset data frame with all rows with a single NaN value removed
maskdrop=mask_subset.dropna()
print(maskdrop)

# Print the shape of the mask_subset data frame with all rows with an NaN values removed
print('Shape',maskdrop.shape)

             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Netherlands     12790.84956     15363.25136     18794.74567
Norway          13450.40151     16361.87647     18965.05551
Shape (2, 3)

## Create new columns

* We can easily create new columns in the same way we would add a key and value to a dictionary

In [180]:
# Create a new column in data frame called diff_07_52 that is the difference between gdp per capita from 1952 to 2007

df_all3['diff_07_52'] = df_all3.gdpPercap_2007-df_all.gdpPercap_1952
#print(df_all3.head(10))
df_all3.loc[:,['gdpPercap_1952','gdpPercap_2007','diff_07_52']]

                          gdpPercap_1952  gdpPercap_2007    diff_07_52
country
Afghanistan                   779.445314      974.580338    195.135024
Albania                      1601.056136     5937.029526   4335.973390
Algeria                      2449.008185     6223.367465   3774.359280
Angola                       3520.610273     4797.231267   1276.620994
Argentina                    5911.315053    12779.379640   6868.064587
Australia                   10039.595640    34435.367440  24395.771800
Austria                      6137.076492    36126.492700  29989.416208
Bahrain                      9867.084765    29796.048340  19928.963575
Bangladesh                    684.244172     1391.253792    707.009620
Belgium                      8343.105127    33692.605080  25349.499953
Benin                        1062.752200     1441.284873    378.532673
Bolivia                      2677.326347     3822.137084   1144.810737
Bosnia and Herzegovina        973.533195     7446.298803   6472.765608
Botswana                      851.241141    12569.851770  11718.610629
Brazil                       2108.944355     9065.800825   6956.856470
Bulgaria                     2444.286648    10680.792820   8236.506172
Burkina Faso                  543.255241     1217.032994    673.777753
Burundi                       339.296459      430.070692     90.774233
Cambodia                      368.469286     1713.778686   1345.309400
Cameroon                     1172.667655     2042.095240    869.427585
Canada                      11367.161120    36319.235010  24952.073890
Central African Republic     1071.310713      706.016537   -365.294176
Chad                         1178.665927     1704.063724    525.397797
Chile                        3939.978789    13171.638850   9231.660061
China                         400.448611     4959.114854   4558.666243
Colombia                     2144.115096     7006.580419   4862.465323
Comoros                      1102.990936      986.147879   -116.843057
Congo Dem. Rep.               780.542326      277.551859   -502.990467
Congo Rep.                   2125.621418     3632.557798   1506.936380
Costa Rica                   2627.009471     9645.061420   7018.051949
...                                  ...             ...           ...
Sierra Leone                  879.787736      862.540756    -17.246980
Singapore                    2315.138227    47143.179640  44828.041413
Slovak Republic              5074.659104    18678.314350  13603.655246
Slovenia                     4215.041741    25768.257590  21553.215849
Somalia                      1135.749842      926.141068   -209.608774
South Africa                 4725.295531     9269.657808   4544.362277
Spain                        3834.034742    28821.063700  24987.028958
Sri Lanka                    1083.532030     3970.095407   2886.563377
Sudan                        1615.991129     2602.394995    986.403866
Swaziland                    1148.376626     4513.480643   3365.104017
Sweden                       8527.844662    33859.748350  25331.903688
Switzerland                 14734.232750    37506.419070  22772.186320
Syria                        1643.485354     4184.548089   2541.062735
Taiwan                       1206.947913    28718.276840  27511.328927
Tanzania                      716.650072     1107.482182    390.832110
Thailand                      757.797418     7458.396327   6700.598909
Togo                          859.808657      882.969944     23.161287
Trinidad and Tobago          3023.271928    18008.509240  14985.237312
Tunisia                      1468.475631     7092.923025   5624.447394
Turkey                       1969.100980     8458.276384   6489.175404
Uganda                        734.753484     1056.380121    321.626637
United Kingdom               9979.508487    33203.261280  23223.752793
United States               13990.482080    42951.653090  28961.171010
Uruguay                      5716.766744    10611.462990   4894.696246
Venezuela                    7689.799761    11415.805690   3726.005929
Vietnam                       605.066492     2441.576404   1836.509912
West Bank and Gaza           1515.592329     3025.349798   1509.757469
Yemen Rep.                    781.717576     2280.769906   1499.052330
Zambia                       1147.388831     1271.211593    123.822762
Zimbabwe                      406.884115      469.709298     62.825183

[142 rows x 3 columns]

---
## EtherPad

On EtherPad explain what the follow expression does:

    only_Am = df[df['continent'] == 'Americas']

___

## EXERCISE:
1. Explain in simple terms what `idxmin` and `idxmax` do in the short program below.
    ~~~
    df = pd.read_csv('data/gapminder_gdp_europe.csv', index_col='country')
    print(df.idxmin())
    print(df.idymax())
    ~~~

2. When would you use these methods?

In [194]:
print(df_all3.diff_07_52.idxmin())
print(df_all3.diff_07_52.idxmax())
df_all3.to_csv('gdpDiff.csv')
#print(df_all3.country.idymax())

Kuwait
Singapore

---
## PRACTICE EXERCISE.
Using the Gapminder GDP data for Europe, write an expression to select each of the following:
1.  GDP per capita for all countries in 1982.
1.  GDP per capita for Denmark for all years.
1.  GDP per capita for all countries for years *after* 1985.
1.  GDP per capita for each country in 2007 as a multiple of GDP per capita for that country in 1952.
---

# -- COMMIT YOUR WORK TO GITHUB --

---
## Keypoints:
 - "Use `DataFrame.iloc[..., ...]` to select values by index location."
 - "Use `:` on its own to mean all columns or all rows."
 - "Select multiple columns or rows using `DataFrame.ix` and a named slice."
 - "Result of slicing can be used in further operations."
 - "Use comparisons to select data based on value."
 - "Select values or NaN using a Boolean mask."